// ---------------------------------------------------------------------------
// mobs.js - GENERATED by tools/assets/build-mobs.py. Do not edit by hand.
//
// The drawings are in art-source/mobs/. Change one there and re-run:
//
//     python tools/assets/build-mobs.py
//
// Each entry is the drawing cropped to its ink, as a pixel map plus the palette
// read off the image - a lossless translation of the file, in the form the rest
// of the bestiary is already written in, so a mob costs no fetch and no decode
// and can be re-rasterised at a new scale without touching the network.
//
// The maps are NOT all the same size, on purpose: a bat is wide and a brute is
// tall. render.js derives a mob's drawn size from its hitbox rather than from
// its pixel count, so the art is free to be authored at whatever resolution
// suits the creature.
// ---------------------------------------------------------------------------

export const MOB_ART = {
  slime: {
    palette: { o: '#123a18', a: '#3f9a45', b: '#6fd66a' },
    rows: [
      '.....oooo.....', '...oobbbboo...', '..obbbbbbbbo..', '.obbbbbbbbbbo.',
      '.obbobbbbobbo.', '.obbbbbbbbbbo.', 'obbbbbbbbbbbbo', 'obbbbbbbbbbbbo',
      'oaaaaaaaaaaaao', 'oaaaaaaaaaaaao', 'oaaaaaaaaaaaao', '.oooooooooooo.',
    ],
  },
  bat: {
    palette: { o: '#2d006d', a: '#ff0000' },
    rows: [
      '............o..o............', '............o..o............',
      '...........oo..oo...........', '.......oo..oooooo..oo.......',
      '.....ooooo.oaooao.ooooo.....', '....ooooooooaooaoooooooo....',
      '...oooooooooooooooooooooo...', '..oooo..oooooooooooo..oooo..',
      '.ooo......oooooooo......ooo.', 'oo.........oooooo.........oo',
      '............oooo............', '.............oo.............',
    ],
  },
  skeleton: {
    palette: { o: '#000000', a: '#0031c5', b: '#ff0000', c: '#8d8d8d', d: '#ff9200' },
    rows: [
      '.a......oooooooo......', '.aa....odddoddcco.....', '.aa...odddodddddco....', '.aa...oddddoddddco....',
      '.aa...odddddddddco....', '.aa...odooddooddco....', '.aa...odbbddbbddco....', '.aa...odddddddddco....',
      '.aa...odddododdcco....', 'oooo..ooddododccoo....', '.oooooooooooooooo.....', '.oddddddddddddccco....',
      '.oooooooooddddoooco...', '.oo.....ododdoco.oco..', '.oo.....oodddcoo..oco.', '........ododdoco...oco',
      '........odddddco....oo', '........oddoocco......', '........odo..oco......', '........odo..oco......',
      '........odo..oco......', '........ooo..ooo......',
    ],
  },
  hound: {
    palette: { o: '#1a0d07', a: '#4f2916', b: '#8a4a2a', c: '#ff7a3c' },
    rows: [
      '.....oooo.....', '...oobbbboo...', '..obbbbbbbbo..', '..obcbbbbcbo..',
      '..obbbbbbbbo..', '.oobbbbbbbboo.', 'obbbbbbbbbbbbo', 'obaaaaaaaaaabo',
      'oaaaaaaaaaaaao', '.oaaaaaaaaaao.', '.oaooaaaaooao.', '.ooo.oaaoo.oo.',
      '......oo......',
    ],
  },
  imp: {
    palette: { o: '#2a0f0c', a: '#8f2a1c', b: '#9c2e1e', c: '#a93220', d: '#b63622', e: '#c33a24', f: '#d03e26', g: '#e0503c', h: '#ffd75e' },
    rows: [
      '.oo........oo.', '.ogoo....oogo.', '..oggooooggo..', '..oggggggggo..',
      '..oghgggghgo..', '..ofggggggfo..', '...oeggggdo...', '.oocggggggdoo.',
      'obggggggggggbo', 'oggaaaaaaaaggo', '.ooaaaaaaaaoo.', '...oaaaaaao...',
      '...oaaaaaao...', '...ooaaaaoo...', '.....oaao.....', '......oo......',
    ],
  },
  brute: {
    palette: { o: '#000000', a: '#1d2410', b: '#ff0000', c: '#614500', d: '#7a4a2a', e: '#4a6a24', f: '#7a9a3c', g: '#d4bb00' },
    rows: [
      '....cccccc....', '....ccaacc....', '..cccaaaaccc..', '.ccaaaggaaaac.',
      'caaaaaggaaaaac', 'cccccaaaaccccc', '..affffffffa..', '..afbffffbfa..',
      '..afbbffbbfa..', '..aoffffffoa..', '.aaoooffoooaa.', 'afafoooooofafa',
      'afafffoofffafa', 'afaddddddddafa', 'afaeeeeeeeeafa', 'oaaeeeeeeeeaao',
      'ooaeeeeeeeeaoo', '..aeeeeeeeea..', '..aeeaaaaeea..', '..aeea..aeea..',
      '..oaao..oaao..', '..oooo..oooo..', '..oooo..oooo..',
    ],
  },
  wisp: {
    palette: { o: '#123244', a: '#2f9ec2', b: '#87cbe3', c: '#93d0e6', d: '#8ef0ff', e: '#f7feff', f: '#ffffff' },
    rows: [
      '........oooo........', '......ooddddoo......', '.....oddddddddo.....', '....oddfddddfddo....',
      '....odeffddeffdo....', '....oddddddddddo....', '....odddaaaadddo....', '.....oaaaaaaaao.....',
      '......ooaaaaoo......', '........oooo........', '....................', '......o..aa..o......',
      '.....oo.a..a.oo.....', '...ooo..a..a..ooo...', 'oooo....a..a....oooo', 'o......aa..aa......o',
      'o...aaaa....aaaa...o', '....a..........a....', '....a....bb....a....', '.........cc.........',
    ],
  },
  spider: {
    palette: { o: '#000000', a: '#f4cc00' },
    rows: [
      '......oo..................oo......', '......oo..................oo......',
      '....oo..oo..oooooooooo..oo..oo....', '....oo..oo..oooooooooo..oo..oo....',
      '..........oooooooooooooo..........', '..........oooooooooooooo..........',
      '....oooooooooooooooooooooooooo....', '....oooooooooooooooooooooooooo....',
      '..oo......oooooooooooooo......oo..', '..oo......oooooooooooooo......oo..',
      'oo....oooooooooooooooooooooo....oo', 'oo....oooooooooooooooooooooo....oo',
      '....oo....ooaaooooooaaoo....oo....', '....oo....ooaaooooooaaoo....oo....',
      '..oo....oo..oooooooooo..oo....oo..', '..oo....oo..oooooooooo..oo....oo..',
      'oo....oo....oo......oo....oo....oo', 'oo....oo....oo......oo....oo....oo',
      '......oo......oo..oo......oo......', '......oo......oo..oo......oo......',
      '......oo..................oo......', '......oo..................oo......',
    ],
  },
  shade: {
    palette: { o: '#000000', a: '#010101', b: '#101010', c: '#6f1918', d: '#ff0000', e: '#912120', f: '#b2272a', g: '#5b5b5b', h: '#afa9a9', i: '#c8c2c2', j: '#d7d1d1', k: '#e6d2d1', m: '#ffffff' },
    rows: [
      '....................hh............', '...................hbbhh..........',
      '.........ccch....hhbaabhj.........', '........ccffah.hhhbaaaaabjj.......',
      '.......cfffffabbbbaaaabaabij......', '......jffffifaaaaaaaabibbibij.....',
      '.....jafiffiiaaaaaaaabiiiiiiij....', '.....iaiibfiaaccccccbiiaiiiiiij...',
      '....jaaibafaacccfffcciiaaiiiiij...', '....jiabaaabbcfcffffcbiiabbbiiij..',
      '....iiabaaabhffffififhijaaahiiij..', '...jiiaaaaaabfafiiiffiibaaabaaiij.',
      '...jabammmaaaaifiiiifiibaaaaaiiij.', '..jiaamaaamaaiiiiiiiiiibaaaaiiiii.',
      '..jiiamadamabiiiiiaaiibammmabiiii.', '..jiibmaaamaaaiiiiiiabamaaambiiii.',
      '..iiibammmaabaaiiiiiaaamadambiiiij', '.iiiaaaaaaabhiaaiiiiibamaaambiiiij',
      '.iiaahbaaaabhiiiiiiibaaammmaaiiiii', '.iiiihbaaaachiiiiiiibaaaaaabaiaiii',
      '.iiiihbaaacehiiiiiiaaaaaaaabhaiiii', '.iiiiihbacefhiiiiaaiabaaaaabhiiiii',
      '.iiiiiihaiifiiiiiiiiihbccccbhiiiii', '.iiiiiiiahfiiiiiiiiiiihhbcehiiiiii',
      '.iiiiiiiaafiiiiiiiiiiiiihefiiiiiih', '.hiiiiiiiaiiiiiiiigiiiiiifiiiiiiih',
      '.hiiiiiiiiiiiiigiigiiiioifiiiiiiih', '.hiiioiiiiiiiihggghiiiiofiiiioiih.',
      '..hiioooiiiiiiihhhiiiiioobboooiih.', '..hiiiioobiiiiiaaiiiibbookkbooooh.',
      '..hiiiookobboiiiaaibakkkooooobiih.', '..hiiiboookkoobbabookoooooooobih..',
      '...hibooooooookkkkooooooooooobih..', '...hioooooooooooooooooooookooiih..',
      '...oooookooooooooooooooooooooih...', '..oohiibooooooooooooooookobioih...',
      '.ooo.hiibokooooooooookkoobiioooo..', '.oooo.hhiboookkookkkoooooiihhooo..',
      'o.o.o...hiobbooooobbobbioo....oo..', '....o.....oiiiiooiiioiiihoo...ooo.',
      '.........oohhhiiooiiohhh.oo...ooo.', '.........oo...hhhohhoo...ooo....o.',
      '........ooo......oo..o...oooo.....', '........o......oooo......oooo.....',
      '...............ooo.o........o.....', '................o.................',
    ],
  },
};

/** The burst colour for a death and the glow on an elite, read off the art. */
export const MOB_ART_TINT = {
  slime: '#6fd66a',
  bat: '#7d3dd9',
  skeleton: '#ff9200',
  hound: '#8a4a2a',
  imp: '#e0503c',
  brute: '#7a9a3c',
  wisp: '#8ef0ff',
  spider: '#f4cc00',
  shade: '#c8c2c2',
};
