# ---------------------------------------------------------------------------
# fetch-fonts.py - vendor the two webfonts so the game has no third-party
# origin at all.
#
#   python tools/assets/fetch-fonts.py
#
# Run once, offline afterwards. Loading these from Google cost three things:
# a DNS lookup and two round trips before first paint on a phone, a privacy
# footprint on every player, and a hole in the Content-Security-Policy that had
# to allow two external hosts. Self-hosting closes all three, and the game then
# works with no network at all.
#
# Only the latin ranges are kept - the interface has no other scripts in it.
# ---------------------------------------------------------------------------
import os, re, urllib.request

HERE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FONT_DIR = os.path.join(HERE, "fonts")
CSS_OUT = os.path.join(HERE, "css", "fonts.css")

# A modern UA is required or Google serves the older, much larger formats.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")
SRC = ("https://fonts.googleapis.com/css2"
       "?family=Silkscreen:wght@400;700"
       "&family=Chakra+Petch:wght@400;500;600;700&display=swap")
KEEP = ("latin", "latin-ext")

os.makedirs(FONT_DIR, exist_ok=True)

def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read() if binary else r.read().decode("utf-8")

css = get(SRC)

# Google's css2 emits a comment naming the unicode range before each @font-face.
blocks = re.findall(r"(/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{[^}]*\})", css)
print(f"  {len(blocks)} faces offered")

out, kept, total = [], 0, 0
for block, subset in blocks:
    if subset not in KEEP:
        continue
    url = re.search(r"url\((https://[^)]+)\)", block).group(1)
    fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
    weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
    name = f"{fam.replace(' ', '')}-{weight}-{subset}.woff2"
    data = get(url, binary=True)
    with open(os.path.join(FONT_DIR, name), "wb") as f:
        f.write(data)
    total += len(data)
    kept += 1
    out.append(block.replace(url, f"../fonts/{name}").strip())
    print(f"  {name:38s} {len(data) // 1024}kb")

header = """/* ---------------------------------------------------------------------------
   Fonts, served from this project rather than from Google.
   Generated by tools/assets/fetch-fonts.py - do not edit by hand.

   Silkscreen and Chakra Petch are both licensed under the SIL Open Font
   License 1.1, which permits redistribution with the software. See
   fonts/OFL.txt.
   --------------------------------------------------------------------------- */
"""
with open(CSS_OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(header + "\n" + "\n\n".join(out) + "\n")

print(f"\n  {kept} faces, {total // 1024}kb total -> css/fonts.css")
